// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvgizqmfjraopucphbli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2Z2l6cW1manJhb3B1Y3BoYmxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMjIwMTQsImV4cCI6MjA2NTU5ODAxNH0.GorBwpkGAmnKpCSguLGLylLJ8qpNi1VBz4Y_O4GEonE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);